# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppbart <- function(x_train, y_train, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump) {
    .Call('_bart5_cppbart', PACKAGE = 'bart5', x_train, y_train, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump)
}

up_tn_sampler <- function(mean_, lower) {
    .Call('_bart5_up_tn_sampler', PACKAGE = 'bart5', mean_, lower)
}

lw_tn_sampler <- function(mean_, upper) {
    .Call('_bart5_lw_tn_sampler', PACKAGE = 'bart5', mean_, upper)
}

cppbart_CLASS <- function(x_train, y_train, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump) {
    .Call('_bart5_cppbart_CLASS', PACKAGE = 'bart5', x_train, y_train, x_test, x_cut, n_tree, node_min_size, n_mcmc, n_burn, tau, mu, tau_mu, alpha, beta, a_tau, d_tau, stump)
}

